version: '3'

services:
  node:
    build:
      context: .
      dockerfile: Dockerfile_node
    volumes:
     - ./:/usr/src/app
    command: sh -c "cd bnavi-hp && yarn install&& yarn start"
    ports:
     - "3000:3000"
